CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
user_name VARCHAR(255) NOT NULL,
password TEXT NOT NULL,
original_password VARCHAR(255) NOT NULL,
created_at DATE NOT NULL DEFAULT CURRENT_DATE
);
CREATE TABLE IF NOT EXISTS transactions(
id SERIAL PRIMARY KEY,
user_id VARCHAR(255) NOT NULL,
title VARCHAR(255) NOT NULL,
amount DECIMAL (10,2) NOT NULL,
category VARCHAR(255),
created_at DATE NOT NULL DEFAULT CURRENT_DATE
);